UsersFake, Votes, ElectionResult
rodrigocontacto/Elections-Challenge-Rodri pull request #4
Opened 2020-02-03 17:02 UTC by rodrigocontacto

2020-02-04 13:02 UTC, MatiasTassara requested changes

2020-02-04 13:02 UTC, MatiasTassara commented on elections.iml
> +<module org.jetbrains.idea.maven.project.MavenProjectsManager.isMavenModule="true" type="JAVA_MODULE" version="4">
Esto no deberia agregarse, fijate como usar el .gitignore

2020-02-04 13:02 UTC, MatiasTassara commented on pom.xml
>  			<groupId>org.springframework.boot</groupId>
El pom tampoco deberia subirse

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/CandidateController.java
> +    private CandidateServiceImpl candidateService;
Tratemos de usar una convencion para los nombres de las clases. Con llamarse CandidateService esta bien

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/CandidateController.java
> +    @ResponseStatus(HttpStatus.CREATED)
El codigo HTTP debe tirarse desde el service. No es responsabilidad de la controler verificar nada , solo que reciba lo que tiene que recibir

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/ElectionController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody BodyElection election, BindingResult result) {
Deberias definirle un dato concreto al ResponseEntity, no es buena practica usar comodines para devolver, cuando ya se sabe lo que vas a devolver

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/UsuarioController.java
> +//@RequestMapping("/api")
en el requestmapping deberia ir /user

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/UsuarioController.java
> +	@GetMapping("/users")
Dentro de una misma controller las rutas deben ser iguales. (al menos las rutas base) Por eso te dije que pongas /user como ruta base de toda la clase.

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/UsuarioController.java
> +	@PutMapping("/usuarios/{id}")
Si no se usa esto lo podrias borrar

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/UsuarioController.java
> +	public ResponseEntity<?> create(@Valid @RequestBody Usuario usuario, BindingResult result) {
No usar comodines

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controllers/UsuarioController.java
> +		this.usuarioService.delete(id);
Acostumbrate a codear en ingles para nombres de variables y clases. Por ahi poarece un tema menor pero es muy importante como llamamops a las variables, clases etc y siempre se acostumbra a que sea en ingles.

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/dao/ICandidateDao.java
> +public interface ICandidateDao extends JpaRepository<Candidate, Long> {
Usar nombre xxxRepository para los repos

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/models/Election.java
> +import lombok.*;
no usar wilcard imports, fijate como corregir esto

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/models/Usuario.java
> +	//@Size(min=3, max=30, message="el tamaño tiene que estar entre 3 a 30")
no dejar codigo comentado, si no se usa, borralo

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/CandidateServiceImpl.java
> +	@Transactional(readOnly=true)
Para hacer solo una operacion en base de datos estaria de mas esta anotacion ya que cada operacion por si sola  si o si es transaccional por defecto.

2020-02-04 13:02 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +    public ResponseEntity<?> createVote(Long idElection, String idUser, BodyVote bodyVote, BindingResult result) {
Fijate como modularizar un poco esta funcion, queda muy larga y no es facil de leer. Aisla las responsabilidades en metodos separados.

2020-02-04 14:24 UTC, ghost requested changes

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +    public ResponseEntity<?> createVote(Long idElection, String idUser, BodyVote bodyVote, BindingResult result) {
El `ResponseEntity<?>` asi con el Wildcard no esta tan bueno. Lo mas prolijo es que responda de un tipo y en caso de error tiras una exception.

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +        ElectionCandidate electionCandidate = null;
Hay que intentar de usar el `null` lo menos posible. El que decidio implementar `null` dijo que fue el error del billon de dolares, te dejo un [articulo](https://medium.com/@hinchman_amanda/null-pointer-references-the-billion-dollar-mistake-1e616534d485 ) si te interesa

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +            electionNew = electionService.findById(idElection);
Acá podrias usar `Optional.orElseThrow()`, asi, si `electionNew = null` tiras la exception que corresponda

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +            electedCandidate = candidateService.findById(bodyVote.getId());
La eleccion que trajiste de Base de datos, tiene un listado de election candidates, podrias recorrer ese listado y devolver el electionCandidate que el usuario quiera votar.

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +            if(existCandidateInElection && user != null ){
`user != null` lo podes evitar utilizando `Optional.orElseThrow()` mas arriba y cortas la ejecución antes.

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +            }
Estas yendo contra la base de datos 4 veces, cuando podrias hacerlo en 2. Cuando vos traes la eleccion desde DB, esta posee una lista de `electionCandidates` los cuales a su vez, poseen cada uno un candidato. Trayendote la eleccion, tenes todos los objetos necesarios para poder realizar el voto.

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/VoteServiceImpl.java
> +    public ResponseEntity<?> createFakeVotes(Long electionId, Long candidateId, BindingResult result){
Fijate, que en vez de recibir un `candidateId`, podrias recibir directamente el `bodyVote`, ya que el objeto para votar o crear votos falsos es el mismo. Entonces no lo armas ahi.

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/UsuarioServiceImpl.java
> +		}
Fijate que el `JPARepository` tiene un metodo saveAll, podrias aprovecharlo

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/UsuarioServiceImpl.java
> +		RestTemplate restTemplate = new RestTemplate();
Podrias crear un bean del tipo restTemplate, ya que puede ser que lo vuelvas a utilizar en otro lado. Solo hace falta tener una instancia del cliente HTTP

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/UsuarioServiceImpl.java
> +		if(fakeUsers != null){
Podrias utilizar un optional ahi, hacer `Optional.ofNulleable(restTemplate.getForObject(url, BodyFakeUsersResults.class)).orElseThrow(...)` y te evitas el` if(fakeUsers != null)`

2020-02-04 14:24 UTC, ghost commented on src/main/java/net/avalith/elections/service/ElectionServiceImpl.java
> +        return ecResults;
podrias hacer un `.stream().forEach(...)` y ahi hacer la logica

2020-02-06 13:43 UTC, ghost requested changes

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controllers/FakeUserController.java
> +        return new ResponseEntity<Map<String, Object>>(response, HttpStatus.CREATED);
En vez de usar un `Map<String,Object>` podrias utilizar una entity

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controllers/FakeUserController.java
> +        response.put("mensaje", "Votos generados correctamente");
Esta respuesta podrias armarla en el service, y que sea una entity

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controllers/FakeUserController.java
> +        response.put("mensaje", "Votos generados correctamente");
Entonces solamente harias `return voteService.createFakeVotes(electionId, candidate, result);`

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controllers/UserController.java
> +	private UserServiceImpl usuarioService;
Por convención, se intenta siempre que las variables estén en ingles

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controllers/UserController.java
> +	public List<User> index() {
Intentá que los nombres de los métodos sean descriptivos y expliquen que hacen de forma clara y concisa

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/models/User.java
> +import javax.persistence.*;
Fijate de configurar el IDE para que los wildcard imports no salgan

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoriesImpl.java
> +    @Scheduled(fixedRate = 3600000)
la idea era que el `fixedRate` sea el que salga en el `applications.properties`

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoriesImpl.java
> +        List<Election> elections = electionService.findAll();
Pordias usar la query custom que hiciste y que solo traiga las activas.

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoriesImpl.java
> +        List<ElectionCandidate> electionCandidate = electionCandidateService.findAll();
La eleccion ya poseé el listado de election candidate que le corresponde a cada uno. Un `select * from election_ candidates` es super costoso ya que hace un `FULL_SCAN` de la tabla

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoriesImpl.java
> +    }
Podrias solucionar todo esto y hacerlo mas legible con un Stream

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoriesImpl.java
> +    }
haces `activeElections.stream().forEach(...)` y comenzas a operar.

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionServiceImpl.java
> +        ecResults.setTotal_votes(count);
Intenta usar streams

2020-02-06 13:43 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionServiceImpl.java
> +                    }
Intenta usar streams en cada for

2020-02-11 15:15 UTC, closed without merging